version: '3.3'

services:

### VSFTPD Container #######################################
            
    vsftpd:
        build:
            context: ./vsftpd
        volumes:
            - ./www/sites/media.keepo:/home/julio/
        environment:
            FTP_USER: julio
            FTP_PASS: pico
            PASV_ADDRESS: 172.16.1.8
            PASV_MIN: 21100
            PASV_MAX: 21110
        restart: always
        networks:
            default:
                ipv4_address: 172.16.1.8

### Redis Container #######################################
    
    redis:
        build:
            context: ./redis
        volumes:
            - redis:/data
        restart: always
        networks:
            default:
                ipv4_address: 172.16.1.7

### Nodes Container #######################################
    
    node:
        build:
            context: ./node
        volumes:
            - ./node/dist:/usr/src/app/dist
        networks:
            default:
                ipv4_address: 172.16.1.9

### PHP-FPM Container #######################################

    php7:
        build:
            context: ./php7
        volumes:
            - ./www:/www
            - ./php7/www.conf:/etc/php7/php-fpm.d/www.conf
        links:
            - "mariadb:mdb"
            - "postgres:pdb"
            - vsftpd
            - redis
        extra_hosts:
            - "keepo.dev:172.16.1.5"
            - "m.keepo.dev:172.16.1.5"
            - "media.keepo.dev:172.16.1.5"
        restart: always
        networks:
            default:
                ipv4_address: 172.16.1.6

### Nginx Server Container ##################################

    nginx:
        build:
            context: ./nginx
        volumes:
            - ./www:/www
            - ./logs/nginx/:/var/log/nginx
            - ./nginx/conf.d/:/etc/nginx/conf.d/
            - ./nginx/nginx-enabled/:/etc/nginx/sites-enabled/
            - ./nginx/base/:/etc/nginx/base/
            - ./nginx/site.conf:/etc/nginx/nginx.conf
        links:
            - php7:php-fpm
            # - node
        restart: always
        networks:
            default:
                ipv4_address: 172.16.1.5

### Nginx Server Container ##################################

    pagespeed:
        build:
            context: ./nginx/pagespeed
        volumes:
            - ./www:/www
            - ./logs/nginx/:/var/log/nginx
            - ./nginx/conf.d/:/etc/nginx/conf.d/
            - ./nginx/base/:/etc/nginx/base/
            - ./nginx/speed-enabled/:/etc/nginx/sites-enabled/
            - ./nginx/pagespeed/nginx.conf:/etc/nginx/nginx.conf
        links:
            - php7:php-fpm
            # - node
        networks:
            default:
                ipv4_address: 172.16.1.5

### MariaDB Container #######################################

    mariadb:
        build: ./mariadb
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - mariadb:/var/lib/mysql
        environment:
            MYSQL_DATABASE: julio_pico
            MYSQL_USER: julio
            MYSQL_PASSWORD: pico
            MYSQL_ROOT_PASSWORD: root
        restart: always
        networks:
            default:
                ipv4_address: 172.16.1.10

### PostgreSQL Container ####################################

    postgres:
        build: ./postgres
        volumes:
            - postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: julio
            POSTGRES_USER: julio
            POSTGRES_PASSWORD: pico
        restart: always
        networks:
            default:
                ipv4_address: 172.16.1.11

volumes:
  mariadb:
    driver: "local"
  redis:
    driver: "local"
  postgres:
    driver: "local"
  sessions:    ## nothing is connected to this (- ./data/sessions:/sessions)
    driver: "local"

networks:
    default:
        driver: bridge
        ipam:
            config:
                - subnet: 172.16.1.0/24
