FROM php:fpm-alpine
RUN set -ex && \
    echo "https://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories && \
    apk update && \
    apk add --no-cache --virtual .php-deps \
    libpq libzip freetype libpng libjpeg-turbo libwebp icu-libs nodejs npm chromium && npm i -g puppeteer && npm cache clean --force && \
    apk add --no-cache --virtual .build-deps $PHPIZE_DEPS \
    libzip-dev postgresql-dev freetype-dev libpng-dev libjpeg-turbo-dev libwebp-dev && \
    docker-php-ext-configure gd \
    --with-freetype --with-webp \
    --with-jpeg=/user/include --enable-gd && \
    NPROC=$(grep -c ^processor /proc/cpuinfo 2>/dev/null || 1) && \
    pecl install redis && \
    docker-php-ext-install -j${NPROC} gd pdo_pgsql pdo_mysql opcache intl zip \
    && docker-php-ext-enable redis \
    && mkdir /www \
    && apk del .build-deps \
    && rm -rf /tmp/* /usr/local/lib/php/doc/* /var/cache/apk/* \
    && echo "opcache.save_comments=1" >> $PHP_INI_DIR/conf.d/docker-php-ext-opcache.ini \
    && rm -rf /tmp/pear ~/.pearrc \
    && rm -rf /var/cache/apk/*

WORKDIR /www

# Expose volumes
VOLUME ["/www"]
